BriefSys/Models/Empleado/ImagenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BriefSys.Models.Empleado
{
    public class ImagenController : Controller
    {
        private EmpleadoContext db = new EmpleadoContext();
        // GET: Imagen
        public ActionResult Show(int IdEmp)
        {
            var dbSetEmpleados = db.empleados;

            var empleadoExistente = from emp in dbSetEmpleados
                                    where emp.IdEmp == IdEmp
                                    select emp;
            var imageData = empleadoExistente.ToList()[0].FotografiaDigital;
            return File(imageData, "image/jpg");
        }
    }
}

BriefSys/Controllers/Home/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BriefSys.Controllers.Home
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
    }
}

BriefSys/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BriefSys.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BriefSys/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BriefSys/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BriefSys/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style>
    .box {
        position: relative;
        width: 100px;
        height: 100px;
        display: inline-block;
    }

    .gray {
        background-color: #a0a0a0
    }

    .dimgray {
        background-color: #5c5c5c
    }

    .box span {
        font-size: 80px;
        font-weight: 500;
        color: white;
    }
</style>

<div style="height:500px; text-align:center;margin-top:8%; overflow:auto;">
    <div class="box gray"><span>B</span></div>
    <div class="box dimgray"><span>R</span></div>
    <div class="box gray"><span>I</span></div>
    <div class="box dimgray"><span>E</span></div>
    <div class="box gray"><span>F</span></div>
    <div class="box dimgray"><span>S</span></div>
    <div class="box gray"><span>Y</span></div>
    <div class="box dimgray"><span>S</span></div>
</div>

<script>
    anime({
        targets: "div.box.gray",
        backgroundColor: '#5c5c5c',
        direction: 'alternate',
        delay: 500,
        duration: 1000,
        loop: true
    });
    anime({
        targets: "div.box.dimgray",
        backgroundColor: '#a0a0a0',
        direction: 'alternate',
        delay: 500,
        duration: 1000,
        loop: true
    });
</script>

BriefSys/Views/Home/SideMenu.cshtml
@model BriefSys.Models.Menu.MenuVM

<link href="~/Content/css/personnel.css" rel="stylesheet" />

<nav id="sidebar" class="bg-dark active">
    <div class="sidebar-header">
        <ul class="list-unstyled components">
            @if (Session["IdEmp"] == null)
            {
                <li>
                    @Html.ActionLink("Registrarse", "Register", "Acceso")
                </li>
                <li>
                    @Html.ActionLink("Iniciar Sesión", "Login", "Acceso")
                </li>
            }
            else
            {
                <li>
                    <div class="text-center">
                        <img src='@Url.Action("Show","Imagen", new { IdEmp = Session["IdEmp"]})' class="imagenPerfil" />
                    </div>
                    <a>
                        @Session["NombreEmpleado"].ToString()
                    </a>
                </li>
                <li>
                    @Html.ActionLink("Cerrar Sesión", "Logout", "Acceso")
                </li>
            }
        </ul>
        <div>
            <h3>Modules</h3>
        </div>
    </div>

    @if (Model != null)
    {
        foreach (var category in Model.Categories)
        {
            <ul class="list-unstyled components">
                <li>
                    <a href='#@category.Category' data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">@category.DisplayName</a>

                    <ul class="collapse list-unstyled" id="@category.Category">
                        @foreach (var menuitem in Model.Items)
                        {
                            if (menuitem.Category == category.Category)
                            {
                                <li>
                                    <a href="@menuitem.Link">@menuitem.LinkName</a>
                                </li>
                            }
                        }
                    </ul>
                </li>
            </ul>
        }
    }

    @*<ul class="list-unstyled components">
            <li>
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>

                <ul class="collapse list-unstyled" id="homeSubmenu">
                    @foreach (var item in Model)
                    {
                        <li>
                            <a href="@item.Link">@item.LinkName</a>
                        </li>
                    }
                </ul>
            </li>
        </ul>*@


    @*
        <ul class="list-unstyled components">
            <li>
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>

                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <a href="#">Home 2</a>
                    </li>
                    <li>
                        <a href="#">Home 3</a>
                    </li>
                </ul>
            </li>

            <li>
                <a href="#">About</a>
            </li>

            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>

                <ul class="collapse list-unstyled" id="pageSubmenu">
                    <li>
                        <a href="#">Page 1</a>
                    </li>
                    <li>
                        <a href="#">Page 2</a>
                    </li>
                    <li>
                        <a href="#">Page 3</a>
                    </li>
                </ul>
            </li>

            <li>
                <a href="#">Portfolio</a>
            </li>

            <li>
                <a href="#">Contact</a>
            </li>

        </ul>*@

</nav>

<script type="text/javascript" src="~/Content/scripts/SidebarMenu.js"></script>